#language: php
#php:
#  - '5.6'
#  - '7.0'
#
#before_script:
#  - cp app/config/parameters.yml.travis app/config/parameters.yml
#  - composer install
#  - php bin/console doctrine:database:create --env=test
#  - php bin/console doctrine:schema:create --env=test

# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
#    - php: 5.5
    - php: 5.6
#    - php: 7.0


before_script:
  - phpenv config-rm xdebug.ini

# Define an environment variable
env:
  - SYMFONY_VERSION="3.2.*" DB=mysql

# Update composer
before-install:
  - mysql -e 'CREATE DATABASE symfony;'
  - composer self-update


# Install composer dependencies,
# Create database, schema and fixtures
#install:
#  - composer install #--no-scripts
#  - cp app/config/parameters.yml.dist app/config/parameters.yml
#  - php bin/console doctrine:database:create --env=test
#  - php bin/console doctrine:schema:create --env=test
#  - php bin/console doctrine:fixtures:load -n --env=test

install:
  - composer install --no-scripts --no-plugins
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test 2> /dev/null || php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

# Run script
script:
  - phpunit tests/
  - phpunit tests/AppBundle/Controller

# After a build, send email notification with the build results
notifications:
  email: david.annebicque@gmail.com