<?php

namespace AppBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('type' => 'asc', 'datedebut' => 'desc'));
    }

    public function findEventComing()
    {
        return $this->createQueryBuilder('c')
            ->where('c.datefin > :date')
            ->setParameter('date', new \DateTime('now'))
            ->orderBy('c.datedebut', 'DESC')
            ->getQuery()
            ->getResult();
    }

}
