<?php

namespace AppBundle\Repository;

/**
 * CategorieProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
