<?php

namespace AppBundle\Repository;

/**
 * ConferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferencesRepository extends \Doctrine\ORM\EntityRepository
{
}
