<?php

namespace AppBundle\Repository;

/**
 * DemandeOMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeOMRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOmsMembre($user)
    {
        return $this->findBy(array('membreCrestic' => $user), array('created' => 'DESC'));
    }
}
