<?php

namespace AppBundle\Repository;

/**
 * EmploisHasProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploisHasProjetsRepository extends \Doctrine\ORM\EntityRepository
{
}
