<?php

namespace AppBundle\Repository;

/**
 * FinanceursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceursRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllFinanceursBuilder()
    {

                return $this->createQueryBuilder('a','a.id')
                    ->orderBy('a.nom', 'ASC');

    }

    /**
     * @return array
     */
    public function findAllFinanceurs()
    {
        return $this->findAllFinanceursBuilder()->getQuery()->getResult();
    }

    public function findInternationaux()
    {
        return $this->createQueryBuilder('p')
            ->where('p.internationale = 1')
            ->orderBy('p.nom', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
