<?php

namespace AppBundle\Repository;

/**
 * MembresExterieursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresExterieursRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */

    public function findAllMembresExterieursBuilder()
    {
        return $this->createQueryBuilder('a','a.id')
            ->orderBy('a.nom', 'ASC');

    }

    /**
     * @return array
     */

    public function findAllMembresExterieurs()
    {
        return $this->findAllMembresExterieursBuilder()->getQuery()->getResult();
    }


    /**
     * @return array
     */
    public function getArrayOfChoiceSelectMembresExterieursAll()
    {
        $result = [];
        $array = $this->findAllMembresExterieurs();
        foreach ($array as $key => $value)
        {
            $result['membreExterieur_'.$key] = $value;
        }

        return $result;
    }

    public function findAllNomMembreExterieursBuilder ($nom)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.nom LIKE :nom')
            ->setParameter('nom',"%".$nom."%");
    }

    public function findAllNomMembreExterieurs ($nom)
    {
        return $this->findAllNomMembreExterieursBuilder($nom)->getQuery()->getResult();
    }




    public function findMembreExterieurBuilder ($data)
    {
        $qb = $this->createQueryBuilder('a','a.id');
        $qb->orderBy('a.nom', 'ASC');
        $nom = $data['nom'];
        if ($nom != '')
        {
            $qb->andWhere('a.nom LIKE :nom');
            $qb->setParameter('nom',"%".$nom."%");
        }

        $prenom = $data['prenom'];
        if ($prenom != '')
        {
            $qb->andWhere('a.prenom LIKE :prenom');
            $qb->setParameter('prenom',"%".$prenom."%");
        }

        $keywords = $data['keywords'];
        if ($keywords != '')
        {
            $qb->where('a.ancienMembresCrestic = 0 AND a.nomLabo LIKE :keywords OR  a.email LIKE :keywords');
            $qb->setParameter('keywords',"%".$keywords."%");
        }

        return $qb;
    }


    public function findMembreExterieur ($data)
    {
        return $this->findMembreExterieurBuilder($data)->getQuery()->getResult();
    }

}
