<?php

namespace AppBundle\Repository;

/**
 * MembresHasReseauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresHasReseauxRepository extends \Doctrine\ORM\EntityRepository
{
}
