<?php

namespace AppBundle\Repository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */

    public function findAllPaysBuilder()
    {
        return $this->createQueryBuilder('a','a.id')
            ->orderBy('a.alpha3', 'ASC');

    }

    /**
     * @return array
     */

    public function findAllPays()
    {
        return $this->findAllPaysBuilder()->getQuery()->getResult();
    }
}
