<?php

namespace AppBundle\Repository;

/**
 * ProjetsHasEquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsHasEquipesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllProjetsFromEquipeBuilder($id_projet)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.projet = ?1')
            ->innerJoin('a.equipe', 'b')
            ->setParameter(1,$id_projet);
    }

    public function findAllProjetsFromEquipe ($id_projet)
    {
        return $this->findAllProjetsFromEquipeBuilder($id_projet)->getQuery()->getResult();
    }

    public function getArrayIdFromProjetsEquipes ($id_projet)
    {
        $result = array();
        $array  =  $this->findAllProjetsFromEquipe($id_projet);

        foreach ($array as $key=>$value)
        {
            $id = $value->getEquipe()->getId();

            $result[] = $id;
        }
        return $result;
    }
}
