<?php

namespace AppBundle\Repository;

/**
 * ProjetsHasFinanceursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsHasFinanceursRepository extends \Doctrine\ORM\EntityRepository
{
}
