<?php

namespace AppBundle\Repository;

/**
 * PublicationsConferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsConferencesRepository extends \Doctrine\ORM\EntityRepository
{
//    public function findLast($nb = 10)
//    {
//        return $this->createQueryBuilder('p')
//            ->orderBy('p.created')
//            ->setMaxResults($nb)
//            ->getQuery()
//            ->getResult();
//    }

    public function findAll()
    {
        return $this->findBy(array(),array('created' => 'DESC'));
    }

    public function getTotal()
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findByAuteurCrestic($id)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('AppBundle:PublicationsHasMembres', 'm', 'WITH', 'p.id = m.publication')
            ->where('m.membreCrestic = :user')
            ->setParameter('user', $id)
            ->orderBy('p.anneePublication', 'desc')
            ->orderBy('p.moisPublication', 'desc')
            ->getQuery()
            ->getResult();
    }
}
