<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PublicationsOuvragesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsOuvragesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(),array('created' => 'DESC'));
    }

    public function findPagination($page, $taille)
    {
        $q = $this->createQueryBuilder('p')
                    //->innerJoin('CRESTICPublicationsBundle:PublicationsHasMembres', 'pm', 'WITH', 'p.id = pm.publication')
                    ->orderBy('p.created', 'DESC')
                    ;

        $q->setFirstResult(($page-1) * $taille)
          ->setMaxResults($taille);

        return new Paginator($q);
    }

    public function getTotal()
    {
        return $this->createQueryBuilder('p')
                ->select('COUNT(p)')
                ->getQuery()
                ->getSingleScalarResult();
    }

    public function findByAuteurCrestic($id)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('AppBundle:PublicationsHasMembres', 'm', 'WITH', 'p.id = m.publication')
            ->where('m.membreCrestic = :user')
            ->setParameter('user', $id)
            ->orderBy('p.anneePublication', 'desc')
            ->orderBy('p.moisPublication', 'desc')
            ->getQuery()
            ->getResult();
    }
}
