<?php

namespace AppBundle\Repository;

/**
 * PublicationsHabilitationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsHabilitationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotal()
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findByAuteurCrestic($id)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('AppBundle:PublicationsHasMembres', 'm', 'WITH', 'p.id = m.publication')
            ->where('m.membreCrestic = :user')
            ->setParameter('user', $id)
            ->orderBy('p.anneePublication', 'desc')
            ->orderBy('p.moisPublication', 'desc')
            ->getQuery()
            ->getResult();
    }
}
