<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PublicationsHasProjets;

/**
 * PublicationsHasProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsHasProjetsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPublicationsFromProjetBuilder($id_publication)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.publication = ?1')
            ->setParameter(1,$id_publication);
    }

    public function findAllPublicationsFromProjet ($id_publication)
    {
        return $this->findAllPublicationsFromProjetBuilder($id_publication)->getQuery()->getResult();
    }

    public function getArrayIdFromPublicationProjets ($id_publication)
    {
        $result = array();
        $array  =  $this->findAllPublicationsFromProjet($id_publication);

        foreach ($array as $key=>$value)
        {
            $id = $value->getProjet()->getId();
            $result[] = $id;
        }
        return $result;
    }

    public function findLastPublicationsFromProjetBuilder($id_projet, $nb)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->innerJoin('CRESTICPublicationsBundle:Publications', 'p', 'WITH', 'a.publication = p.id')
            ->where('a.projet = ?1')
            ->setParameter(1, $id_projet)
            ->orderBy('p.anneePublication', 'DESC')
            ->orderBy('p.moisPublication', 'DESC')
            ->setMaxResults($nb);
    }

    public function findLastPublicationsFromProjet ($id_projet, $nb)
    {
        return $this->findLastPublicationsFromProjetBuilder($id_projet, $nb)->getQuery()->getResult();
    }

    public function findAllIdProjets($idpublication)
    {
        $projets = $this->findAllPublicationsFromProjet($idpublication);
        $t =array();
        /** @var PublicationsHasProjets $e */
        foreach ($projets as $e)
        {
            $t[$e->getProjet()->getId()] = $e;
        }

        return $t;
    }
}
