<?php

namespace AppBundle\Repository;
use Doctrine\DBAL\Query\QueryBuilder;

/**
 * PublicationsBrevetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsBrevetsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(),array('created' => 'DESC'));
    }

    /*public function findAllFiltre()
    {
    Test pour renvoyer que les champs qu'il faut sur les filtres car cela prend beaucoup de mémoire
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select   ('publication.id')
            ->addSelect('publication.titre')
            ->addSelect('publication.dateDelivrance')
            ->addSelect('publication.numeroDelivrance')
            ->addSelect('publication.pays')
            ->from    ('CRESTICPublicationsBundle:PublicationsBrevets','publication');

        $query   = $queryBuilder->getQuery();
        $results =$query->getResult();

        return $results;

    }*/

    public function getTotal()
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findByAuteurCrestic($id)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('AppBundle:PublicationsHasMembres', 'm', 'WITH', 'p.id = m.publication')
            ->where('m.membreCrestic = :user')
            ->setParameter('user', $id)
            ->orderBy('p.anneePublication', 'desc')
            ->orderBy('p.moisPublication', 'desc')
            ->getQuery()
            ->getResult();
    }

}
