<?php

namespace AppBundle\Repository;

/**
 * ReseauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauxRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllReseauxBuilder($array_options = null)
    {
        $result = null;

        switch ($array_options['role'])
        {
            case 'ROLE_ADMINISTRATEUR':
            {
                $result =  $this->createQueryBuilder('a','a.id')
                    ->orderBy('a.nom', 'ASC');
                break;
            }

            case 'ROLE_RESPONSABLE':
            {
                $result =  $this->createQueryBuilder('a','a.id')
                    ->orderBy('a.nom', 'ASC');

                break;
            }

            case 'ROLE_UTILISATEUR':
            {
                $result =  $this->createQueryBuilder('a','a.id')
                    ->orderBy('a.nom', 'ASC');
                break;
            }

            case 'ROLE_VISITEUR':
            {
                break;
            }

            default :
            {
                $result =  $this->createQueryBuilder('a','a.id')
                    ->orderBy('a.nom', 'ASC');
                break;
            }
        }

        return $result;
    }

    /**
     * @param null $array_options
     *
     * @return array
     */

    public function findAllReseaux($array_options = null)
    {
        return $this->findAllReseauxBuilder($array_options)->getQuery()->getResult();
    }
}
