<?php

namespace AppBundle\Repository;

/**
 * RevuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevuesRepository extends \Doctrine\ORM\EntityRepository
{
}
