imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
        - 'AppBundle::form.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        configuration: "@kernel.configuration"
        biblio: "@kernel.biblio"
        html: "@kernel.html"


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            sluggable: true
            timestampable: true
            translatable: true

fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    AppBundle\Entity\MembresCrestic # La classe de l'entité User que nous utilisons
    from_email:
        address:        intranet-crestic@crestic.univ-reims.fr
        sender_name:    Intranet CReSTIC

vich_uploader:
    db_driver: orm
    mappings:
        actualites_images:
            uri_prefix:         /uploads/actualites
            upload_destination: '%kernel.root_dir%/../web/uploads/actualites'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        plateformes_images:
            uri_prefix:         /uploads/plateformes
            upload_destination: '%kernel.root_dir%/../web/uploads/plateformes'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        equipes_images:
            uri_prefix:         /uploads/equipes
            upload_destination: '%kernel.root_dir%/../web/uploads/equipes'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        emplois_pdf:
            uri_prefix:        /uploads/emplois
            upload_destination: '%kernel.root_dir%/../web/uploads/emplois'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        projets_images:
            uri_prefix:         /uploads/projets
            upload_destination: '%kernel.root_dir%/../web/uploads/projets'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        publications_pdf:
            uri_prefix:        /uploads/publications
            upload_destination: '%kernel.root_dir%/../web/uploads/publications'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        membresCrestic_images:
            uri_prefix:        /uploads/membresCrestic
            upload_destination: '%kernel.root_dir%/../web/uploads/membresCrestic'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
#        reseaux_images:
#            uri_prefix:         /uploads/reseaux
#            upload_destination: '%kernel.root_dir%/../web/uploads/reseaux'
#            delete_on_update:   true
#            delete_on_remove:   true
#            namer:              vich_uploader.namer_uniqid
        slider_images:
            uri_prefix:         /uploads/slider
            upload_destination: '%kernel.root_dir%/../web/uploads/slider'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        partenaires_images:
            uri_prefix:         /uploads/partenaires
            upload_destination: '%kernel.root_dir%/../web/uploads/partenaires'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        document_images:
            uri_prefix:         /uploads/documents
            upload_destination: '%kernel.root_dir%/../web/uploads/documents'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        ri_images:
            uri_prefix:         /uploads/ri
            upload_destination: '%kernel.root_dir%/../web/uploads/ri'
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

services:
    fos_user.doctrine_registry:
        alias: doctrine

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: /media/cache

    filter_sets:
        cache: ~
        avatar:
            jpeg_quality: 80
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        partenaire:
            jpeg_quality: 80
            filters:
                #thumbnail: { size: [120, 120], mode: inset }
                relative_resize: { widen: 120 }
        slider:
            jpeg_quality: 80
            filters:
                #thumbnail: { size: [120, 120], mode: inset }
                #relative_resize: { widen: 300 }
                thumbnail: { size: [120, 300], mode: outbound }

        profil:
            jpeg_quality: 80
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        ppe:
            jpeg_quality: 80
            filters:
                thumbnail: { widen: 540, mode: outbound }