
#force:
#    path:     /force
#    defaults: { _controller: AppBundle:Default:force }
#
#l3_logout:
#    path:     /logout
#    defaults: { _controller: L3CasBundle:Logout:logout }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /{_locale}
    defaults: {_locale:fr}
    requirements:
        _locale:  '|fr|en'




# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

