app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /{_locale}
    defaults: {_locale:fr}
    requirements:
        _locale:  '|fr|en'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"