# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\MembresCrestic: bcrypt

    role_hierarchy:
        ROLE_UTILISATEUR: ROLE_USER
        ROLE_RESPONSABLE: ROLE_UTILISATEUR
        ROLE_ADMINISTRATEUR: ROLE_RESPONSABLE


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main

            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path : true
                default_target_path: /fr/espace-utilisateur
                #success_handler: authentication.handler.login_success_handler
            logout:
                path: fos_user_security_logout
                target: /
#            remember_me:
#                key:      "%secret%"
#                lifetime: 20592000 #31536000 # 365 jours en secondes
#                path:     /
#                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

    access_control:
        - { path: ^/[a-z][a-z]/espace-utilisateur/, role: [ROLE_UTILISATEUR, ROLE_ADMINISTRATEUR] }
        - { path: ^/[a-z][a-z]/responsable/, role: ROLE_RESPONSABLE }
        - { path: ^/[a-z][a-z]/administration/, role: ROLE_ADMINISTRATEUR }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
