# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    kernel.configuration:
        class: AppBundle\Services\ConfigurationManager
        arguments: ["@doctrine.orm.entity_manager"]
    kernel.biblio:
        class: AppBundle\Services\Biblio
        arguments: ["@doctrine.orm.entity_manager", '@kernel.html']
    kernel.html:
        class: AppBundle\Services\Html
        arguments: ['@router']

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments: ['@router']
        tags:
            - { name: twig.extension }

    my.mailer:
            class: AppBundle\Services\MyMailer
            arguments: ['@mailer', '@templating']